sudo: false
language: node_js
node_js:
- "6"

env:
  matrix:
  - BROWSER=chrome  BVER=stable
  - BROWSER=chrome  BVER=beta
  - BROWSER=chrome  BVER=unstable
  - BROWSER=firefox BVER=stable
  - BROWSER=firefox BVER=beta
  - BROWSER=firefox BVER=nightly

services:
  - xvfb

matrix:
  fast_finish: true

  allow_failures:
    - env: BROWSER=chrome  BVER=unstable
    - env: BROWSER=firefox BVER=unstable

before_script:
  - ./node_modules/travis-multirunner/setup.sh
  - export DISPLAY=:99.0

notifications:
  email:
  - nathan+rtcio@coviu.com
